


/*
--------------------------------------------------------------------------------------------------------------------------------------------------
MAGNITUDE EXPLORATION Divide a [MEASURE]/ [DIMENSION]
--------------------------------------------------------------------------------------------------------------------------------------------------
*/
-- Total Customers by country
SELECT   country,
         count(customer_key) AS no_customers
FROM     gold.dim_customers
GROUP BY country
ORDER BY no_customers DESC;


-- Total Customers by gender
SELECT   gender,
         count(customer_key) AS no_customers
FROM     gold.dim_customers
GROUP BY gender
ORDER BY no_customers DESC;


-- Total Products by category

SELECT   category,
         count(product_key) AS no_products
FROM     gold.dim_products
GROUP BY category
ORDER BY no_products DESC;

-- What is average cost in each category
SELECT   category,
         AVG(cost) AS avg_cost
FROM     gold.dim_products
--WHERE category is not null
GROUP BY category
ORDER BY avg_cost DESC 


-- What is total revenue generated for each category
SELECT   p.category,
         SUM(sales_amount) AS total_revenue
FROM     gold.fact_sales AS f
         LEFT  JOIN
         gold.dim_products AS p
         ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


 
-- Find total revenue generated by each customer

SELECT   c.customer_key,c.first_name, c.last_name,
         SUM(f.sales_amount) AS total_revenue
FROM     gold.fact_sales AS f
         LEFT JOIN
         gold.dim_customers AS c
         ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of the sold items across countries
 
SELECT   country,
         sum(quantity) AS qty
FROM     gold.fact_sales AS f
         LEFT OUTER JOIN
         gold.dim_customers AS c
         ON f.customer_key = c.customer_key
GROUP BY country
ORDER BY qty DESC;
